#!/bin/bash
clear
echo "America/Sao_Paulo" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime > /dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1
IP=$(wget -qO- ipv4.icanhazip.com)
clear
echo -e "\E[44;1;37m    INSTALL THE SSH / DROP / SSL PANEL     \E[0m" 
echo ""
echo -ne "\n\033[1;32mSET A PASSWORD FOR O\033[1;33m MYSQL\033[1;37m: "; read password
echo -e "\n\033[1;36mSTARTING INSTALLATION \033[1;33mWAIT..."
apt-get update -y > /dev/null 2>&1
apt-get install cron curl unzip -y > /dev/null 2>&1
echo -e "\n\033[1;36mINSTALLING APACHE2 \033[1;33mWAIT...\033[0m"
apt-get install apache2 -y > /dev/null 2>&1
apt-get install php5 libapache2-mod-php5 php5-mcrypt -y > /dev/null 2>&1
service apache2 restart > /dev/null 2>&1
echo -e "\n\033[1;36mINSTALLING MySQL \033[1;33mWAIT...\033[0m"
echo "debconf mysql-server/root_password password $PASSWORD" | debconf-set-selections
echo "debconf mysql-server/root_password_again password $PASSWORD" | debconf-set-selections
apt-get install mysql-server -y > /dev/null 2>&1
mysql_install_db > /dev/null 2>&1
(echo $PASSWORD; echo n; echo y; echo y; echo y; echo y)|mysql_secure_installation > /dev/null 2>&1
echo -e "\n\033[1;36mINSTALLING O PHPMYADMIN \033[1;33mWAIT...\033[0m"
echo "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections
echo "phpmyadmin phpmyadmin/app-password-confirm password $PASSWORD" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/admin-pass password $PASSWORD" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/app-pass password $PASSWORD" | debconf-set-selections
echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2" | debconf-set-selections
apt-get install phpmyadmin -y > /dev/null 2>&1
php5enmod mcrypt > /dev/null 2>&1
service apache2 restart > /dev/null 2>&1
ln -s /usr/share/phpmyadmin /var/www/html/phpmyadmin
apt-get install libssh2-1-dev libssh2-php -y > /dev/null 2>&1
if [ "$(php -m |grep ssh2)" = "ssh2" ]; then
  true
else
  clear
  echo -e "\033[1;31m CRITICAL ERROR\033[0m"
  rm $HOME/install.sh
  exit
fi
apt-get install php5-curl > /dev/null 2>&1
service apache2 restart > /dev/null 2>&1
clear
echo ""
echo -e "\033[1;31m ATTENTION \033[1;33m!!!"
echo ""
echo -ne "\033[1;32m INFORM THE SAME PASSWORD\033[1;37m: "; read password
sleep 1
mysql -h localhost -u root -p$PASSWORD -e "CREATE DATABASE sshplus"
clear
echo -e "\033[1;36m FINISHING INSTALLATION\033[0m"
echo ""
echo -e "\033[1;33m WAIT..."
echo ""

cd /var/www/html
wget https://www.dropbox.com/s/sjzgmbjkrzxa5wc/v20.zip > /dev/null 2>&1
unzip v20.zip > /dev/null 2>&1
rm -rf v20.zip index.html > /dev/null 2>&1
service apache2 restart > /dev/null 2>&1
sleep 1
if [[ -e "/var/www/html/pages/system/pass.php" ]]; then
sed -i "s;1010;$PASSWORD;g" /var/www/html/pages/system/pass.php > /dev/null 2>&1
fi
sleep 1
cd
wget https://raw.githubusercontent.com/radzvpn/SSHPLUS-MANAGER-FREE/master/Install/Panel_Web/panel_v20/banco.sql > /dev/null 2>&1
sleep 1
if [[ -e "$HOME/banco.sql" ]]; then
    mysql -h localhost -u root -p$PASSWORD --default_character_set utf8 sshplus < banco.sql
    rm /root/banco.sql
else
    clear
    echo -e "\033[1;31m ERROR IMPORTING DATABASE\033[0m"
    sleep 2
    rm /root/install.sh > /dev/null 2>&1
    exit
fi
service apache2 restart > /dev/null 2>&1
clear
echo '* * * * * root /usr/bin/php /var/www/html/pages/system/cron.php' >> /etc/crontab
echo '* * * * * root /usr/bin/php /var/www/html/pages/system/cron.ssh.php ' >> /etc/crontab
echo '* * * * * root /usr/bin/php /var/www/html/pages/system/cron.sms.php' >> /etc/crontab
echo '* * * * * root /usr/bin/php /var/www/html/pages/system/cron.online.ssh.php' >> /etc/crontab
echo '10 * * * * root /usr/bin/php /var/www/html/pages/system/cron.servidor.php' >> /etc/crontab
echo '*/30 * * * * root /usr/bin/php /var/www/html/pages/system/cron.limpeza.php' >> /etc/crontab
echo '*/1 * * * * root /bin/html.sh' >> /etc/crontab
cd /bin
wget https://raw.githubusercontent.com/radzvpn/SSHPLUS-MANAGER-FREE/master/Install/Panel_Web/panel_v20/html.sh > /dev/null 2>&1 && chmod 777 html.sh && sed -i -e 's/\r$//' html.sh && ./html.sh
/etc/init.d/cron reload > /dev/null 2>&1
/etc/init.d/cron restart > /dev/null 2>&1
cd
chmod 777 /var/www/html/admin/pages/servidor/ovpn
chmod 777 /var/www/html/admin/pages/download
chmod 777 /var/www/html/admin/pages/faturas/comprovantes
service apache2 restart > /dev/null 2>&1
clear
echo -e "\033[1;32m SUCCESSFULLY INSTALLED SSH PANEL!"
echo ""
echo -e "\033[1;36m YOUR PANEL:\033[1;37m http://$IP/admin\033[0m"
echo -e "\033[1;36m USER:\033[1;37m admin\033[0m"
echo -e "\033[1;36m PASSWORD:\033[1;37m admin\033[0m"
echo ""
echo -e "\033[1;33m Change PASSWORD when you log in to the panel>> Settings>> PASSWORD Antiga: admin >> New PASSWORD: \033[0m"
cat /dev/null > ~/.bash_history && history -c
rm /root/install
